name: Fedora RPM Fabrikasi
on: [push]
jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - name: Gerekli Kutuphaneleri Kur
        run: dnf install -y gcc-c++ cmake rpm-build qt6-qtbase-devel
      - name: Derle ve Paketle
        run: |
          mkdir build && cd build
          cmake ..
          make
          cpack -G RPM
      - name: RPM Paketini Cikti Olarak Ver
        uses: actions/upload-artifact@v4
        with:
          name: ro-assist-fedora-rpm
          path: build/*.rpm
